# permissions for end users to view ngnixoperatorhelmcharts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ngnixoperatorhelmchart-viewer-role
rules:
- apiGroups:
  - charts.fr.wilda
  resources:
  - ngnixoperatorhelmcharts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.fr.wilda
  resources:
  - ngnixoperatorhelmcharts/status
  verbs:
  - get
